CatalogoWebMVC/Models/PaginacionViewModel.cs
namespace CatalogoWebMVC.Models
{
    public class PaginacionViewModel
    {
        public int Pagina { get; set; } = 1;

        private int registrosPorPagina = 5;

        private readonly int cantidadMaximaRegitrosPorPagina = 50;

        public int CantidadTotalRegistros { get; set; } // segun el tipo de consulta


        public int RegistrosPorPagina
        {
            get { return registrosPorPagina; }
            set { registrosPorPagina = value > 50 ? cantidadMaximaRegitrosPorPagina : value; }
        }

        public int RegistrosASaltar => registrosPorPagina * (Pagina - 1);

    }
}

CatalogoWebMVC/Controllers/ArticuloController.cs
using CatalogoWebMVC.Data;
using Microsoft.AspNetCore.Mvc;
using CatalogoWebMVC.Models;
using Microsoft.AspNetCore.Mvc.Rendering;
using CatalogoWebMVC.Services;
using AutoMapper;
using Microsoft.EntityFrameworkCore;
using System.Text.RegularExpressions;
using System;
using Microsoft.AspNetCore.Authorization;

namespace CatalogoWebMVC.Controllers
{
    public class ArticuloController : Controller
    {
        private IRepositorioArticulos repositorio;
        private IRepositorioMarcas repositorioMarcas;
        private IRepositorioCategorias repositorioCategorias;
        private IMapper mapper;
        public ArticuloController(IRepositorioArticulos repositorio,
            IRepositorioMarcas repositorioMarcas, 
            IRepositorioCategorias repositorioCategorias,
            IMapper mapper)
        {
            this.repositorio = repositorio;
            this.repositorioMarcas = repositorioMarcas;
            this.repositorioCategorias = repositorioCategorias;
            this.mapper = mapper;
        }
        public IActionResult Index(int Pagina, int RegistrosPorPagina)
        {

            PaginacionViewModel paginaViewModel = new PaginacionViewModel();

            if (Pagina != 0 && RegistrosPorPagina != 0)
            {
                paginaViewModel.Pagina = Pagina;
                paginaViewModel.RegistrosPorPagina = RegistrosPorPagina;

            }

            // Obtenemos una pagina desde el repositorio
            var paginaMostrar = repositorio.ObtenerPaginaArticulo(paginaViewModel);

            //Cargamos una pagina en PaginacionRespuesta
            var pagina = new PaginacionRespuesta<Articulo>
            {
                Elementos = paginaMostrar,
                Pagina = paginaViewModel.Pagina,
                CantidadTotalRegistros = paginaViewModel.CantidadTotalRegistros,
                RegistrosPorPagina = paginaViewModel.RegistrosPorPagina,

                // Asigna la url completa de la accion y controlador
                BaseUrl = Url.Action()

            };


            return View(pagina);
        }

        public IActionResult FormularioAlta()
        {
            ArticuloViewModel articuloNuevo = new ArticuloViewModel();

            //var listaMarcas = (from m in db.Marcas select new SelectListItem { Text = m.Descripcion.ToString(), Value = m.Id.ToString() }).ToList();
            //var listaCategorias = (from c in db.Categorias select new SelectListItem { Text = c.Descripcion.ToString(), Value = c.Id.ToString() }).ToList();
            var listaMarcas = repositorioMarcas.ObtenerItems();
            var listaCategorias = repositorioCategorias.ObtenerItems();

            articuloNuevo.Marca = listaMarcas;
            articuloNuevo.Categoria = listaCategorias;

            return View(articuloNuevo);
        }

        [HttpPost]
        public IActionResult FormularioAlta(ArticuloViewModel modelo)
        {
            if (modelo != null)
            {
                repositorio.AgregarArticulo(modelo.ToArticulo());

            }

            return RedirectToAction("Index");
        }

        public IActionResult ArticulosLista()
        {
            ArticulosListaViewModel modelo = new ArticulosListaViewModel();
            modelo.ListadoArticulos =  repositorio.ObtenerArticulos().ToList();
            modelo.FiltroModelo = new FiltroViewModel();
            Campo campo = Campo.Nombre;
            modelo.FiltroModelo.Criterio = ObtenerCriterio(campo).ToList();
            return View(modelo);
        }

        public IActionResult Detalle(int IdProducto)
        {
            var articuloSeleccionado = repositorio.ObtenerArticulo(IdProducto);
            var articulo = articuloSeleccionado.ToViewModel();
            articulo.Categoria = repositorioCategorias.ObtenerItems();
            articulo.Marca = repositorioMarcas.ObtenerItems();
            return View(articulo);
        }

        [Authorize]
        public IActionResult ModificarArticulo(int IdProducto)
        {
            var articuloSeleccionado = repositorio.ObtenerArticulo(IdProducto).ToViewModel();
            articuloSeleccionado.Categoria = repositorioCategorias.ObtenerItems();
            articuloSeleccionado.Marca = repositorioMarcas.ObtenerItems();

            return View(articuloSeleccionado);
        }

        [HttpPost]
        public IActionResult ModificarArticulo(ArticuloViewModel articulo)
        {
            Articulo articuloGuardar = articulo.ToArticulo();

            repositorio.ModificarArticulo(articuloGuardar);

            return RedirectToAction("Index");
        }

        public IActionResult EliminarArticulo(ArticuloViewModel articulo)
        {
            int idArticulo = articulo.Id;
            Articulo artBorrar = repositorio.ObtenerArticulo(idArticulo);
            repositorio.BorrarArticulo(artBorrar);

            return RedirectToAction("Index");
        }

        public IActionResult FiltroRapido(string Buscar)
        {
            List<Articulo> lista = repositorio.BuscarArticulo(Buscar);
            return View("ArticulosLista", lista);
        }

        [HttpPost]
        public IActionResult FiltroAvanzado(bool estado)
        {
            if (estado)
            {
                FiltroViewModel filtroViewModel = new FiltroViewModel();
                filtroViewModel.Campo = new List<SelectListItem>()
                {
                    new SelectListItem{ Text="Nombre", Value = "1", Selected = true },
                    new SelectListItem{ Text="Descripcion", Value = "2" },
                    new SelectListItem{ Text="Precio", Value = "3" }
                };
                filtroViewModel.Criterio = new List<SelectListItem>()
                {
                    new SelectListItem { Text = "Comienza con", Value = "1"},
                    new SelectListItem { Text = "Termina con", Value = "2"},
                    new SelectListItem { Text = "Igual a", Value = "3" }
                };


                return PartialView("_FiltroAvanzado", filtroViewModel);
            }
            else
                return PartialView("_FiltroAvanzadoVacio");
        }

        [HttpPost]
        public async Task<IActionResult> ObtenerCriterios([FromBody] Campo valorSeleccionado)
        {
            

            return Ok(ObtenerCriterio(valorSeleccionado));
        }

        private IEnumerable<SelectListItem> ObtenerCriterio(Campo valorSeleccionado)
        {
            List<SelectListItem> ListaCriterio;

            if (valorSeleccionado == Campo.Nombre || valorSeleccionado == Campo.Descripcion)
            {
                ListaCriterio = new List<SelectListItem>()
                {
                    new SelectListItem { Text = "Comienza con", Value = "1"},
                    new SelectListItem { Text = "Termina con", Value = "2"},
                    new SelectListItem { Text = "Igual a", Value = "3" }
                };
            }
            else
            {
                ListaCriterio = new List<SelectListItem>()
                {
                    new SelectListItem { Text = "Mayor a", Value = "1"},
                    new SelectListItem { Text = "Menor a", Value = "2"},
                    new SelectListItem { Text = "Igual a", Value = "3" }
                };
            }

            return ListaCriterio;
        }

        [HttpPost]
        public IActionResult BusquedaAvanzada(FiltroViewModel filtro)
        {


            //return Json(new { resultado = "Exito" });
            return PartialView("_CuerpoListaArticulos", repositorio.BusquedaAvanzada(filtro));
            
        }

        [HttpGet]
        public IActionResult Buscar(string buscar = "")
        {
            var listaArticulos = repositorio.ObtenerArticulos().ToList();
            var listaFiltrada = listaArticulos;

            if (!string.IsNullOrEmpty(buscar) && buscar.Length > 3)
                listaFiltrada = listaArticulos.FindAll(x => x.Nombre.ToUpper().Contains(buscar.ToUpper()) || 
                                                            x.Descripcion.ToUpper().Contains(buscar.ToUpper()));

            return PartialView("_CuerpoListaArticulos", listaFiltrada);

        }

        // Agregados para trabajar con JQuery Data Table
        // El resultado seran datos para el script de paginado JQ
        [HttpGet]
        public JsonResult ListaArticulos()
        {
            var Lista = ListarAVM();

            return Json(new { data = Lista });
        }

        [HttpGet]
        public IActionResult AdmProductos()
        {
            var Lista = ListarAVM();

            return View("AdmProductos", Lista);
        }

        public List<ArticuloViewModelDT> ListarAVM()
        {
            List<ArticuloViewModelDT> Lista = new List<ArticuloViewModelDT>();
            var listaA = repositorio.ObtenerArticulos();
            var listaM = repositorioMarcas.ObtenerMarcas();
            var listaC = repositorioCategorias.ObtenerCategorias();

            Lista = (from a in listaA
                     select new ArticuloViewModelDT
                     {
                         Id = a.Id,
                         Codigo = a.Codigo,
                         Nombre = a.Nombre,
                         Descripcion = a.Descripcion,
                         IdMarca = a.IdMarca,
                         Marca = (from m in listaM where m.Id == a.IdMarca select m.Descripcion).First(),
                         IdCategoria = a.IdCategoria,
                         Categoria = (from c in listaC where c.Id == a.IdCategoria select c.Descripcion).First(),
                         ImagenUrl = a.ImagenUrl,
                         Precio = a.Precio
                     }).ToList();

            return Lista;
        }


    }

   
}

CatalogoWebMVC/Controllers/UsuariosController.cs
using CatalogoWebMVC.Data;
using CatalogoWebMVC.Models;
using CatalogoWebMVC.Servicios;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Scaffolding;

namespace CatalogoWebMVC.Controllers
{
    public class UsuariosController : Controller
    {
        private readonly UserManager<IdentityUser> userManager;
        private readonly SignInManager<IdentityUser> signInManager;
        private readonly CATALOGO_WEB_DBContext contexto;
        public UsuariosController(UserManager<IdentityUser> userManager,
            SignInManager<IdentityUser> signInManager, CATALOGO_WEB_DBContext contexto)
        {
            this.userManager = userManager;
            this.signInManager = signInManager;
            this.contexto = contexto;
        }

        [AllowAnonymous]
        public IActionResult Registro()
        {
            return View();
        }

        [HttpPost]
        [AllowAnonymous]
        public async Task<IActionResult> Registro(RegistroViewModel modelo)
        {
            if(!ModelState.IsValid)
            {
                return View(modelo);
            }

            // Creamos una instancia de Identity user con los datos del modelo
            var usuario = new IdentityUser() { Email = modelo.Email, UserName = modelo.Email };

            // Creamos un registro de usuario
            var resultado = await userManager.CreateAsync(usuario, password: modelo.Passwoord);

            if (resultado.Succeeded)
            {
                await signInManager.SignInAsync(usuario, isPersistent: true);
                return RedirectToAction("Index", "Home");
            }
            else
            {
                foreach(var error in resultado.Errors)
                {
                    ModelState.AddModelError(string.Empty, error.Description);

                }
                return View(modelo);
            }
        }

        [AllowAnonymous]
        public IActionResult Login()
        {
            return View();
        }

        [HttpPost]
        [AllowAnonymous]
        public async Task<IActionResult> Login(LoginViewModel modelo)
        {
            if(!ModelState.IsValid)
            {
                return View(modelo);
            }

            var resultado = await signInManager.PasswordSignInAsync(modelo.Email, modelo.Password,
                modelo.Recuerdame, lockoutOnFailure: false);

            if (resultado.Succeeded)
            {
                return RedirectToAction("Index", "Home");
            }
            else
            {
                ModelState.AddModelError(string.Empty, "Nombre de usuario o password incorrecto");
                return View(modelo);
            }
        }

        [HttpPost]
        public async Task<IActionResult> Logout()
        {
            await HttpContext.SignOutAsync(IdentityConstants.ApplicationScheme);
            return RedirectToAction("Index", "Home");
        }

        [HttpGet]
        [Authorize(Roles = Constantes.RolAdmin)]
        public async Task<IActionResult> Listado(string mensaje = null)
        {
            var usuarios = await contexto.Users.Select(u=> new UsuarioViewModel
            {
                Email = u.Email
            }).ToListAsync();

            var modelo = new UsuariosListadoViewModel();
            modelo.Usuarios = usuarios;
            modelo.Mensaje = mensaje;
            return View(modelo);
        }

        [HttpPost]
        [Authorize(Roles = Constantes.RolAdmin)]
        public async Task<IActionResult> HacerAdmin(string email)
        {
            var usuario = await contexto.Users.Where(u => u.Email == email).FirstOrDefaultAsync();
            
            if (usuario is null)
            {
                return NotFound();
            }

            await userManager.AddToRoleAsync(usuario, Constantes.RolAdmin);

            return RedirectToAction("Listado",
                routeValues: new { mensaje = "Rol asignado correctamente a " + email });
        }

        [HttpPost]
        [Authorize(Roles = Constantes.RolAdmin)]
        public async Task<IActionResult> RemoverAdmin(string email)
        {
            var usuario = await contexto.Users.Where(u => u.Email == email).FirstOrDefaultAsync();

            if (usuario is null)
            {
                return NotFound();
            }

            await userManager.RemoveFromRoleAsync(usuario, Constantes.RolAdmin);

            return RedirectToAction("Listado",
                routeValues: new { mensaje = "Rol removido correctamente a " + email });
        }



    }
}

CatalogoWebMVC/Views/Shared/_CuerpoListaArticulos.cshtml
@using CatalogoWebMVC.Data
@model IEnumerable<Articulo>

    <div class="row">
        <div class="col-12">
            <table class="table">
                <thead>
                    <tr>
                        <th>
                            @Html.DisplayNameFor(model => model.Codigo)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Nombre)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Descripcion)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.IdMarca)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.IdCategoria)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Precio)
                        </th>

                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.Codigo)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Nombre)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Descripcion)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.IdMarca)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.IdCategoria)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Precio)
                            </td>
                            <td>
                                @Html.ActionLink("✍", "ModificarArticulo", new {  IdProducto=item.Id })
                            </td>

                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>

CatalogoWebMVC/Views/Shared/_FiltroAvanzado.cshtml
@model FiltroViewModel



<div class="container">
    <form id="AjaxForm">
        <div class="row">
            <div class="col-12 col-sm-3">
                <div class="mb-3">
                    <label class="control-label">Campo</label>
                    <select id="IdCampo" asp-for="IdCampo" asp-items="Html.GetEnumSelectList<CatalogoWebMVC.Models.Campo>()" class="form-select"></select>
                </div>
            </div>
            <div class="col-12 col-sm-3">
                <div class="mb-3">
                    <label class="control-label">Criterio</label>
                    <select id="IdCriterio" asp-for="TextoCriterio" asp-items="Model.Criterio" class="form-select"></select>
                </div>
            </div>
            <div class="col-12 col-sm-3">
                <div class="mb-3">
                    <label class="control-label" asp-for="Texto">Texto</label>
                    <input id="Texto" asp-for="Texto" type="text" placeholder="texto de busqueda" class="form-control" />
                </div>
            </div>
            <div class="col-12 col-sm-3" style="display: flex; flex-direction: column; justify-content: flex-end;">
                <div class="mb-3">
                    <button id="btnAvanzado" type="submit" class="btn btn-primary">Buscar</button>
                </div>
            </div>
        </div>

    </form>
</div>



<script>

    $(function () {

        $("#IdCampo").change(function () {
            const valorSeleccionado = $(this).val();
            const urlCriterio = '@Url.Action("ObtenerCriterios")';

            $.ajax({
                url: urlCriterio,
                type: 'POST',
                data: valorSeleccionado,
                contentType: 'application/json',
                success: function (result) {
                    // console.log(result);
                    const criterio = result.map(criterio => `<option value=${criterio.value}>${criterio.text}</option>`);
                    $("#IdCriterio").html(criterio);
                },
                error: function () {
                    console.log("Error en la solicitud AJAX")
                }
            });

            console.log(valorSeleccionado);
        });

        

        $("#AjaxForm").submit(function (e) {
                e.preventDefault();
                console.log("Me dolio mucho tu click");

                const IdCampo = $("#IdCampo").val();
                const IdCriterio = $("#IdCriterio").val();
                const Texto = $("#Texto").val();

            $.ajax({
                type: 'POST',
                url: "@Url.Action("BusquedaAvanzada", "Articulo")",
                data: {
                    IdCampo: $("#IdCampo").val(),
                    IdCriterio: $("#IdCriterio").val(),
                    Texto: $("#Texto").val(),
                    TextoCriterio: $("#IdCriterio").children(":selected").text(),
                    TextoCampo: $("#IdCampo").children(":selected").text()
                },

                success: function (result) {
                    console.log(result);
                    console.log("Resultado feliz");
                },
                error: function () {
                    console.log("Error en la solicitud AJAX")
                }
            });
                
         });

        })

</script>

CatalogoWebMVC/Views/Shared/_Layout.cshtml
@using CatalogoWebMVC.Servicios;
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CatalogoWebMVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CatalogoWebMVC.styles.css" asp-append-version="true" />
    <!-- Font Awesome -->
    <link rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.min.css"
          integrity="sha512-xh6O/CkQoPOWDdYTDqeRdPCVd1SpvCA9XXcUnZS2FmJNp1coAFzvtCN9BmamE+4aHK8yyUHUSCcJHgXloTyT2A=="
          crossorigin="anonymous"
          referrerpolicy="no-referrer" />
    @await RenderSectionAsync("Styles", required: false)
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Articulo" asp-action="Index">CatalogoWebMVC</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Articulo" asp-action="Index">Home</a>
                        </li>
                        @if (User.IsInRole(Constantes.RolAdmin))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Articulo" asp-action="AdmProductos">Adm Articulos</a>
                            </li>
                        }
                        
                        @if(User.IsInRole(Constantes.RolAdmin))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Usuarios" asp-action="Listado">Listado de usuarios</a>
                            </li>
                        }
                            
                    </ul>
                    <partial name="_LinksLogin" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - CatalogoWebMVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

CatalogoWebMVC/Views/Shared/_LinksLogin.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager

<ul class="navbar-nav">
     @if (SignInManager.IsSignedIn(User))
    {
        <li class="nav-item">
            <span class="nav-link text-dark">Hola, @User.Identity.Name</span>
        </li>
        <li class="nav-item">
            <form class="form-inline" asp-action="logout" asp-controller="usuarios">
                <button type="submit" class="nav-link btn btn-link text-dark">
                    Logout
                </button>
            </form>
        </li>
    }
    else
        {
            <li class="nav-item">
                <a class="nav-link dark-text" asp-controller="usuarios" asp-action="Registro">
                    Registro
                </a>
            </li>

        <li class="nav-item">
            <a class="nav-link dark-text" asp-controller="usuarios" asp-action="Login">
                Login
            </a>
        </li>
        }
</ul>

CatalogoWebMVC/Views/Shared/_Paginacion.cshtml
@model PaginacionRespuesta

@{
    // Concatenamos BaseUsel con el querystring
    string plantillaLink = string.Concat(Model.BaseUrl, "?Pagina={0}&RegistrosPorPagina={1}");

    // Si la pagina es mayor a 1 podemos activar el boton
    // Acivar el boton siguiente si la pagina actual no es la ultima
    var activarBotonAnterior = Model.Pagina > 1;
    var activarBotonSiguiente = Model.Pagina < Model.CantidadTotalPaginas;

}

<nav>
    <ul class="pagination">

        @* Boton Anterior - activar o desactivar - agregarle el link correspondiente *@

       <li class="page-item @(activarBotonAnterior ? null : "disabled")">
           @if(activarBotonAnterior)
            {
                <a class="page-link" href="@string.Format(plantillaLink, Model.Pagina - 1 , Model.RegistrosPorPagina)">
                        Anterior
                </a>
            }
            else
            {
                <span class="page-link">Anterior</span>
            }
                
       </li>
       


        @for(var pagina = 1; pagina <= Model.CantidadTotalPaginas; pagina++)
        {
            <li class="page-item @(pagina == Model.Pagina ? "active" : null)">
                <a class="page-link" href="@string.Format(plantillaLink, pagina, Model.RegistrosPorPagina)">@pagina</a>
            </li>
        }

        @* Boton Siguiente *@
        <li class="page-item @(activarBotonSiguiente ? null : "disabled")">

            @if(activarBotonSiguiente)
            {
                <a class="page-link" href="@string.Format(plantillaLink, Model.Pagina + 1, Model.RegistrosPorPagina)">Siguiente</a>
            }
            else
            {
                <span class="page-link">Siguiente</span>
            }
                
        </li>
    </ul>

</nav>